---
version: '3.7'

services:
  demo-lb-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DEMO-LB-APP 
    environment:
      - APP_VERSION=v1.0.1
    restart: always
    ports:
      - "8882:8882/tcp"