apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo-lb-app

resources:
- deployment.yaml
- ingress.yaml
- namespace.yaml
- service.yaml
- hpa.yaml

namespace: demo-lb-app

images:
- name: jmanzur/demo-lb-app:latest
  newName: jmanzur/demo-lb-app
  newTag: latest

configMapGenerator:
- literals:
  - APP_VERSION=v1.0.0
  name: lb-app-cm

labels:
- includeSelectors: true
  pairs:
    owner: jmanzur

patches:
- patch: |-
    - op: replace
      path: /spec/maxReplicas
      value: 6
  target:
    kind: HorizontalPodAutoscaler
    name: demo-lb-app-hpa