name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'images/**'
      - 'kubernetes/**'
      - 'scripts/**'

env:
  IMAGE_NAME: demo-lb-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
  
    steps:
    - name: Get the application source code
      uses: actions/checkout@v3

    - name: Echo the image name for debugging
      run: echo "Building the image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx # https://github.com/marketplace/actions/docker-buildx-bake
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
    
    - name: Security Scan using Snyk
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
        args: --file=Dockerfile --severity-threshold=critical --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif